# Generated by Django 5.2.7 on 2025-11-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BOMConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schachttyp", models.CharField(max_length=100)),
                ("hvb_size", models.CharField(max_length=50)),
                ("sonden_durchmesser", models.CharField(max_length=10)),
                ("sondenanzahl", models.IntegerField()),
                ("sondenabstand", models.IntegerField()),
                ("anschlussart", models.CharField(max_length=50)),
                (
                    "kugelhahn_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dfm_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mother_article_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "child_article_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "full_article_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_existing_configuration", models.BooleanField(default=False)),
                ("is_existing_mother_article", models.BooleanField(default=False)),
                ("zuschlag_links", models.IntegerField(default=100)),
                ("zuschlag_rechts", models.IntegerField(default=100)),
            ],
            options={
                "verbose_name_plural": "BOM Configurations",
            },
        ),
        migrations.CreateModel(
            name="CSVDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("file_path", models.CharField(max_length=500)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DFM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("durchflussarmatur", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("et_hvb", models.CharField(blank=True, max_length=200, null=True)),
                ("et_sonden", models.CharField(blank=True, max_length=200, null=True)),
                ("dfm_hvb", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "DFMs",
            },
        ),
        migrations.CreateModel(
            name="Entlueftung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Entlüftungen",
            },
        ),
        migrations.CreateModel(
            name="GNXChamberArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hvb_size_min", models.IntegerField()),
                ("hvb_size_max", models.IntegerField()),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                ("is_automatic", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "GN X Chamber Articles",
            },
        ),
        migrations.CreateModel(
            name="HVB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hauptverteilerbalken", models.CharField(max_length=50)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "HVBs",
            },
        ),
        migrations.CreateModel(
            name="Kugelhahn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kugelhahn", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("et_hvb", models.CharField(blank=True, max_length=200, null=True)),
                ("et_sonden", models.CharField(blank=True, max_length=200, null=True)),
                ("kh_hvb", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "Kugelhähne",
            },
        ),
        migrations.CreateModel(
            name="Schacht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schachttyp", models.CharField(max_length=100, unique=True)),
                (
                    "artikelnummer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "artikelbezeichnung",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Schächte",
            },
        ),
        migrations.CreateModel(
            name="Schachtgrenze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Schachtgrenzen",
            },
        ),
        migrations.CreateModel(
            name="Schachtkompatibilitaet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Schachtkompatibilitäten",
            },
        ),
        migrations.CreateModel(
            name="Sondenabstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sondenabstand", models.IntegerField()),
                ("anschlussart", models.CharField(max_length=50)),
                ("zuschlag_links", models.IntegerField()),
                ("zuschlag_rechts", models.IntegerField()),
                ("hinweis", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "Sondenabstände",
            },
        ),
        migrations.CreateModel(
            name="Sondengroesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("durchmesser_sonde", models.CharField(max_length=10)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                ("schachttyp", models.CharField(max_length=100)),
                ("hvb", models.CharField(max_length=50)),
                ("bauform", models.CharField(blank=True, max_length=50, null=True)),
                ("sondenanzahl_min", models.IntegerField(blank=True, null=True)),
                ("sondenanzahl_max", models.IntegerField(blank=True, null=True)),
                (
                    "ruecklauf_laenge",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "vorlauf_laenge",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "vorlauf_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ruecklauf_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("hinweis", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name_plural": "Sondengrößen",
            },
        ),
        migrations.CreateModel(
            name="Sondenverschlusskappe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Sondenverschlusskappen",
            },
        ),
        migrations.CreateModel(
            name="StumpfschweissEndkappe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Stumpfschweiss-Endkappen",
            },
        ),
        migrations.CreateModel(
            name="Verrohrung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verrohrung", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Verrohrungen",
            },
        ),
        migrations.CreateModel(
            name="WPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "WPAs",
            },
        ),
        migrations.CreateModel(
            name="WPVerschlusskappe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                (
                    "menge_statisch",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "menge_formel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "WP-Verschlusskappen",
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artikelnummer", models.CharField(max_length=50)),
                ("artikelbezeichnung", models.CharField(max_length=200)),
                ("menge", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "calculated_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("source_table", models.CharField(max_length=50)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="configurator.bomconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "BOM Items",
            },
        ),
        migrations.CreateModel(
            name="GNXChamberConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "bom_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurator.bomconfiguration",
                    ),
                ),
                (
                    "gnx_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configurator.gnxchamberarticle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GN X Chamber Configurations",
            },
        ),
    ]
