# Generated by Django 5.2.7 on 2025-12-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_entlueftung_et_hvb'),
    ]

    operations = [
    ]
