# Generated by Django 5.2.7 on 2025-12-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_auto_20251208_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schachtgrenze',
            name='artikelbezeichnung',
        ),
        migrations.RemoveField(
            model_name='schachtgrenze',
            name='artikelnummer',
        ),
        migrations.RemoveField(
            model_name='schachtgrenze',
            name='menge_formel',
        ),
        migrations.RemoveField(
            model_name='schachtgrenze',
            name='menge_statisch',
        ),
        migrations.RemoveField(
            model_name='schachtgrenze',
            name='name',
        ),
        migrations.AddField(
            model_name='schachtgrenze',
            name='erlaubte_hvb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schachtgrenze',
            name='hinweis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schachtgrenze',
            name='max_sondenanzahl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schachtgrenze',
            name='schachttyp',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
