# Generated by Django 5.2.7 on 2025-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_remove_schachtgrenze_artikelbezeichnung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVBStuetze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvb_durchmesser', models.CharField(max_length=10)),
                ('position', models.CharField(choices=[('Oben', 'Oben'), ('Unter', 'Unter')], max_length=10)),
                ('artikelnummer', models.CharField(max_length=50)),
                ('artikelbezeichnung', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'HVB Stützen',
                'unique_together': {('hvb_durchmesser', 'position')},
            },
        ),
    ]
