# Generated by Django 5.2.7 on 2025-12-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_hvbstuetze'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomconfiguration',
            name='rücklauf_kugelhahn_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
