# Generated by Django 5.2.7 on 2025-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_bomconfiguration_rücklauf_kugelhahn_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomconfiguration',
            name='rücklauf_kugelhahn_type',
        ),
        migrations.AddField(
            model_name='bomconfiguration',
            name='dfm_kugelhahn_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
