# Generated by Django 5.2.6 on 2026-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_remove_bomconfiguration_rücklauf_kugelhahn_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SondenDurchmesser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schachttyp', models.CharField(max_length=100)),
                ('durchmesser', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Sonden Durchmesser',
                'ordering': ['schachttyp', 'durchmesser'],
                'unique_together': {('schachttyp', 'durchmesser')},
            },
        ),
    ]
