# Generated by Django 5.2.6 on 2026-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_sondendurchmesser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SondenDurchmesserPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durchmesser', models.CharField(max_length=10, unique=True)),
                ('artikelnummer', models.CharField(max_length=50)),
                ('artikelbezeichnung', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sonden Durchmesser Pipes',
                'ordering': ['durchmesser'],
            },
        ),
    ]
