# Generated by Django 5.2.6 on 2026-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_sondendurchmesserpipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondenbeschriftung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=50)),
                ('artikel', models.CharField(max_length=200)),
                ('menge_statisch', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('menge_formel', models.CharField(blank=True, max_length=200, null=True)),
                ('schaechte', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sondenbeschriftungen',
            },
        ),
    ]
