# Generated by Django 5.2.6 on 2026-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0011_sondenbeschriftung'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpa',
            name='wp_durchmesser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
