# Generated by Django 5.2.6 on 2026-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0012_wpa_wp_durchmesser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomconfiguration',
            name='hvb_stuetze_quantities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomconfiguration',
            name='ruecklauf_length_per_probe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bomconfiguration',
            name='vorlauf_length_per_probe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bomconfiguration',
            name='wp_diameter_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bomconfiguration',
            name='wp_pipe_length_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
